LoadSkins()
PETS_DATABASE.Add(new PetBase(PET_TYPE.CAT,"Cat","Um gato"))
PETS_DATABASE.Add(new PetBase(PET_TYPE.CHICKEN,"Chick","Um pinto"))
PETS_DATABASE.Add(new PetBase(PET_TYPE.CHICKEN,"Chicken","Uma galinha"))
PETS_DATABASE.Add(new PetBase(PET_TYPE.COW,"Cow","Uma vaca"))
PETS_DATABASE.Add(new PetBase(PET_TYPE.DOG,"Dog","Um cachorro"))
PETS_DATABASE.Add(new PetBase(PET_TYPE.BIRD,"Eagle","Uma aguia"))
PETS_DATABASE.Add(new PetBase(PET_TYPE.DOG,"Fox","Uma raposa"))
PETS_DATABASE.Add(new PetBase(PET_TYPE.COW,"Pig","Um porco"))
PETS_DATABASE.Add(new PetBase(PET_TYPE.BIRD,"Pigeon","Um pombo"))
PETS_DATABASE.Add(new PetBase(PET_TYPE.DOG,"Wolf","Um lobo"))