LoadSkins()
PETS_DATABASE.Add(new PetBase(PET_TYPE.CAT,"Cat","Um gato",10))
PETS_DATABASE.Add(new PetBase(PET_TYPE.CHICKEN,"Chick","Um pinto",20))
PETS_DATABASE.Add(new PetBase(PET_TYPE.CHICKEN,"Chicken","Uma galinha",30))
PETS_DATABASE.Add(new PetBase(PET_TYPE.COW,"Cow","Uma vaca",40))
PETS_DATABASE.Add(new PetBase(PET_TYPE.DOG,"Dog","Um cachorro",50))
PETS_DATABASE.Add(new PetBase(PET_TYPE.BIRD,"Eagle","Uma aguia",60))
PETS_DATABASE.Add(new PetBase(PET_TYPE.DOG,"Fox","Uma raposa",70))
PETS_DATABASE.Add(new PetBase(PET_TYPE.COW,"Pig","Um porco",80))
PETS_DATABASE.Add(new PetBase(PET_TYPE.BIRD,"Pigeon","Um pombo",90))
PETS_DATABASE.Add(new PetBase(PET_TYPE.DOG,"Wolf","Um lobo",100))